version: '3.8'

services:
  go:
    container_name: go-app
    platform: linux/x86_64
    hostname: localhost
    ports:
      ## - 3000:3000 #　デバッグ用のポート フロントで被ったので一旦コメントアウト
      - 8080:8080
    tty: true
    build:
      context: ./golang/
      dockerfile: Dockerfile
    volumes:
      - ./golang:/go/src
    depends_on:
      - db
    networks:
      - lesson

  frontend:
    container_name: react-todo
    build:
      context: ./react-todo/
      dockerfile: Dockerfile
    volumes:
      - ./react-todo:/usr/src/app
    ports:
      - "3000:3000"
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    networks:
      - lesson

  db:
    image: postgres:15.1-alpine
    container_name: dev-postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    restart: always
    volumes:
      - db-store:/var/lib/postgresql/data
    networks:
      - lesson

volumes:
  db-store:

networks:
  lesson: