version: '3.8'

services:
  go:
    container_name: go-app
    platform: linux/x86_64
    hostname: localhost
    ports:
      - 3000:3000 #　デバッグ用のポート
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/go/src
    depends_on:
      - db
    networks:
      - lesson

  db:
    image: postgres:15.1-alpine
    container_name: dev-postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    restart: always
    volumes:
      - db-store:/var/lib/postgresql/data
    networks:
      - lesson

volumes:
  db-store:

networks:
  lesson: