version: '3'

services:
  go:
    container_name: go-api-server
    platform: linux/x86_64
    hostname: localhost
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/go/src/app